repos:
  #  - repo: https://github.com/hadialqattan/pycln
  #    rev: "v2.1.2"
  #    hooks:
  #      - id: pycln
  #        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.3.1"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
      - id: black-jupyter
        args: [--target-version=py310]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        exclude: "templates|bootstrap|vendor"
