repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.4.0"
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.15.0"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-pyupgrade
        args: ["--py310-plus"]
      - id: nbqa-isort
        args: ["--float-to-top"]
  - repo: https://github.com/ambv/black
    rev: "23.11.0"
    hooks:
      - id: black-jupyter
        args: [--target-version=py310]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
